name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyserial pillow pygame

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name TOH_MRI_Trigger_Music_Player serial_usb_monitor_gui.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: TOH_MRI_Trigger_Music_Player_Windows_EXE
          path: dist/TOH_MRI_Trigger_Music_Player.exe
